### ISSUE TITLE
preserve accents

### ISSUE THREAD

**Issue by ghost** [matthewmorrone/cmudict-ipa#1]
Would it be possible to preserve accents, at least the main ones (those marked with 1)?

**Comment by matthewmorrone** [comment]
If I remember correctly, passing in "true" for the second parameter preserves those, like this:

```
php main.php cmu.ipa.tsv true > cmudict.ipa.tsv
```

This will make it spit out "ˈ" for primary stress and "ˌ" for secondary stress, which is the IPA's equivalent of Arpabet's numerical suffixes.

Let me know if that doesn't work or if I misunderstood your question!

**Comment by ghost** [comment]
Thank’you very much for answering! 
Actually there’s something strange happening: issuing this command (or even just php main.php cmu.ipa.tsv > cmudict.ipa.tsv) will create a cmudict.ipa.tsv file that contains the php script itself, not the dictionary (??). 
Can you reproduce this too? I’m on archlinux, with php v5.6.9

**Comment by ghost** [comment]
Update: problem solved! i had to: 
1. replace the <? header with <?php in both main.php and strPadUnicode.php
Now a warning appeared:
PHP Warning:  include(): open_basedir restriction in effect. File(/data/cmudict-ipa/strPadUnicode.php) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/)
So:
2. move the folder to one of this paths: /srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/

Now everything works, the "true" option too!
